### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by hitched97** [yulyugin/cpuid-g#1]
Support for FreeBSD would be appreciated.  I may take a stab at converting the linux kernel module to a FreeBSD kernel module myself, if I can find some time.

**Comment by yulyugin** [comment]
That should be easy to add. I installed FreeBSD on my RaspberryPi and started to work on the port in [freebsd](https://github.com/yulyugin/cpuid-g/tree/freebsd) branch. I will probably finish it soon but it of course depends on the amount of time I can allocate to work the issue.

**Comment by yulyugin** [comment]
I pushed my changes to master branch. I will also review your pull request and try to integrate some part of it as well a bit later.
